---

- name: Install packages
  command: npm install -g pm2@{{ pm2_version }} --unsafe-perm
  notify: restart pm2
  with_items:
    - pm2
  tags:
    - web
    - pm2
    - install

- name: installing startup script
  command: >
    pm2 -s startup {{ pm2_startup }} -u {{ pm2_startup_user }}
  tags:
    - web
    - pm2
    - install
