---

- name: Starting apps
  command: pm2 start {{ item }}
  with_items: pm2_apps
  tags:
    - web
    - pm2
    - manage
  when: pm2_startup_user == 'root'

- name: Starting apps
  command: pm2 start {{ item }}
  with_items: pm2_apps
  tags:
    - web
    - pm2
    - manage
  sudo: yes
  sudo_user: '{{ pm2_startup_user }}'
  when: pm2_startup_user != 'root'

- name: installing startup script
  command: >
    pm2 -s startup {{ pm2_startup }} -u {{ pm2_startup_user }}
  tags:
    - web
    - pm2
    - install

- name: kill pm2 root daemon if startup is specifying another user 
  command: >
    pm2 kill
  when: pm2_startup_user != 'root'